url: http://keps.cool
email: kepskast@keps.cool
podcast_feed: http://keps.cool/kepskast/podcast.xml
iTunes_url: "#iTunes"

permalink: /:categories/:title

defaults:
    -
        scope:
            path: ""
            type: post
        values:
            layout: episode