url: http://www.keps.cool
email: kepskast@keps.cool
podcast_feed_url: http://www.keps.cool/kepskast/rss.xml
iTunes_url: "#iTunes"

permalink: /:categories/:title

defaults:
    -
        scope:
            path: "kepskast"
            type: post
        values:
            layout: episode