url: http://kepskast.github.io
email: kepskollektivet@gmail.com
iTunes_url: "#iTunes"

permalink: /:title

defaults:
    -
        scope:
            path: ""
            type: post
        values:
            layout: episode